- name: download epel rpm
  shell: "wget --no-check-certificate http://download.fedoraproject.org/pub/epel/6/x86_64/{{ epel_filename }} -O {{ epel_rpm }} creates={{ epel_rpm }}"

- name: yum install epel (Extra Packages for Enterprise Linux)
  shell: "yum -y --nogpgcheck localinstall {{ epel_rpm }}"
  sudo: yes

# install the hadoop packages
- name: Fetch HDP repo
  shell: "wget http://public-repo-1.hortonworks.com/HDP-2.0.0.2/repos/centos6/hdp.repo -O /etc/yum.repos.d/hdp.repo creates=/etc/yum.repos.d/hdp.repo"
  sudo: yes

- name: yum install hadoop
  yum: name='hadoop' state=installed
  sudo: yes

- name: yum install hadoop-hdfs
  yum: name='hadoop-hdfs' state=installed
  sudo: yes

- name: yum install hadoop-libhdfs
  yum: name='hadoop-libhdfs' state=installed
  sudo: yes

- name: yum install hadoop-yarn
  yum: name='hadoop-yarn' state=installed
  sudo: yes

- name: yum install hadoop-mapreduce
  yum: name='hadoop-mapreduce' state=installed
  sudo: yes

- name: yum install hadoop-client
  yum: name='hadoop-client' state=installed
  sudo: yes

- name: yum install openssl
  yum: name='openssl' state=installed
  sudo: yes

# install snappy compression
- name: yum install snappy
  yum: name='snappy' state=installed
  sudo: yes

- name: yum install snappy-devel
  yum: name='snappy-devel' state=installed
  sudo: yes

# install lzo compression
- name: yum install lzo
  yum: name='lzo' state=installed
  sudo: yes

- name: yum install lzo-devel
  yum: name='lzo-devel' state=installed
  sudo: yes

- name: yum install hadoop-lzo
  yum: name='hadoop-lzo' state=installed
  sudo: yes

- name: yum install hadoop-lzo-native
  yum: name='hadoop-lzo-native' state=installed
  sudo: yes
